spring.application.name=journaling-app

spring.datasource.url=jdbc:mysql://localhost:3306/journaldb
spring.datasource.username=root
spring.datasource.password=journal3326!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true